import json
import requests
import logging
from secrets import spotify_user_id, spotify_token

class BPM_Playlist():
    # initializer
    def __init__(self):
        self.user_id = spotify_user_id
        self.token = spotify_token
        self.uris = []

    # get songs based on filters
    def get_songs(self):
        # get api endpoint to recommendations object 
        endpoint_url = "https://api.spotify.com/v1/recommendations?"

        # query filters
        limit = 20
        seed_genres = "alternative,indie,rock"
        min_tempo = 170
        target_tempo = 170

        # query the recommendations 
        query = f'{endpoint_url}limit={limit}&seed_genres={seed_genres}&target_tempo={target_tempo}&min_tempo{min_tempo}'

        response = requests.get(query, 
                    headers = {"Content-Type":"application/json", "Authorization":f"Bearer {self.token}"})

        json_response = response.json()

        print('Recommended Songs:')
        for i,j in enumerate(json_response['tracks']):
                    self.uris.append(j['uri'])
                    print(f"{i+1}. {j['name']} by {j['artists'][0]['name']}")


    # create new playlist
    def create_playlist(self):
        endpoint_url = f"https://api.spotify.com/v1/users/{self.user_id}/playlists"

        request_body = json.dumps({
                "name": "BPM 170 using Python",
                "description": "Python autogenerated playist",
                "public": False
                })

        response = requests.post(url = endpoint_url, 
                                data = request_body, 
                                headers = {"Content-Type":"application/json","Authorization":f"Bearer {self.token}"})

        # return response to get playlist id
        return response.json()['id']
    
    # add songs to the new playlist
    def add_songs(self):
        # query songs to add
        self.get_songs()

        # create new playlist and get playlist id
        playlist_id = self.create_playlist()

        endpoint_url = f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks"

        request_body = json.dumps({
                "uris" : self.uris
                })
                
        response = requests.post(url = endpoint_url, 
                                data = request_body, 
                                headers = {"Content-Type":"application/json","Authorization":f"Bearer {self.token}"})

        print(f"status: {response.status_code}")

# run program
if __name__ == "__main__":
    bp = BPM_Playlist()
    bp.get_songs()
    bp.add_songs()